### ISSUE TITLE
Add a User API

### ISSUE THREAD

**Issue by ro0NL** [msgphp/symfony-demo-app#10]
Basically integration with https://github.com/api-platform and perhaps some `User\Infra\Api` infra. Dunno :) will be the first time using API platform for me.

In general goal is to have e.g. `/api/user`  endpoints, including docs.

**Comment by Evertt** [comment]
Cool idea man! Though I guess the PR that's still open has a higher priority right?

**Comment by ro0NL** [comment]
@Evertt yes, that is #7 / basic user management. Next would be the multiple user types (https://github.com/msgphp/msgphp/issues/41).

**Comment by ro0NL** [comment]
Superseded by #31
