### ISSUE TITLE
Demo Site is down

### ISSUE THREAD

**Issue by tacman** [msgphp/symfony-demo-app#106]
https://msgphp.lndo.site doesn't connect at all 

http://msgphp.lndo.site/ redis fails to connect

**Comment by ro0NL** [comment]
Hi @tacman,

The `.lando.site` domain is part of the local development workflow when using Lando: https://docs.devwithlando.io

So it's not intended to work remote (unless one shares their local setup publicly using https://docs.devwithlando.io/cli/share.html)

I removed the link from github, as it was mostly a personal shortcut (or for anyone using Lando).

The demo app doesnt use redis, so im not sure that's related.

Closing as such.

**Comment by ro0NL** [comment]
If you intended to run it locally, `lando rebuild` should work out-of-the-box.
