### ISSUE TITLE
Shell for user-bundle demo with bootstrap and jquery

### ISSUE THREAD

**Issue by tacman** [msgphp/symfony-demo-app#115]
Although my landing-bundle isn't complete yet, here are steps that will create a basic website with menus and a login form, using the msgphp user-bundle:

    symfony new --full my-app && cd my-app
    composer config extra.symfony.allow-contrib true

    composer req survos/landing-bundle
    bin/console survos:prepare --no-interaction
    composer req maker --dev
    composer req messenger msgphp/user-bundle -n
    bin/console make:user:msgphp --no-interaction
    bin/console doctrine:schema:update --force
    bin/console survos:setup --no-interaction
    symfony server:start 

Yarn, composer and the symfony server need to be installed, of course.

I'm jazzed about enhancing this!

**Comment by ro0NL** [comment]
hey @tacman very nice :+1: i just released 0.13 so you can move forward :)

im closing here (ive bookmarked your project), feel free to ask any help (e.g. Slack) concerning msgphp integration.

If you have some tutorial blog post about msgphp (integration), im happy to share it in the readme file here.

keep up the good work :+1:
