### ISSUE TITLE
How to change the default ROLE_USER?

### ISSUE THREAD

**Issue by crabnky** [msgphp/symfony-demo-app#15]
Hi,
I'm trying to change the default ROLE_USER to something else - for example ROLE_DEFAULT. This is because I'm taking roles from the database and there is ROLE_USER already defined, so logged user has ROLE_USER duplicated. How do I do this?

Thanks!

**Comment by ro0NL** [comment]
In the default app we get user roles from `App\Security\UserRolesProvider`

https://github.com/msgphp/symfony-demo-app/blob/ee5358a9b16dcb07e83732d555297e213eaf920b/src/Security/UserRolesProvider.php#L18-L25

You can change this as you like :)

We also populate some database roles in https://github.com/msgphp/symfony-demo-app/blob/master/src/DataFixtures/ORM/Users.php#L60

**Comment by crabnky** [comment]
HUH, how did I miss this?  ❓ 
Thank you much!
