### ISSUE TITLE
How can I get the first name of the authenticated user?

### ISSUE THREAD

**Issue by crabnky** [msgphp/symfony-demo-app#19]
Hello,
My user entity has a first name. How can I get the first name of the authenticated user? For example I want to display `Hello {{ app.user.firstName }}` in twig template. How to play with serialization?
Thanks.

**Comment by ro0NL** [comment]
Hi :)

By default the concept is to assign a user from your controller, as a template variable. Being either the current user or a known one, or both even :)

This is not yet documented or has a demo, but you have 2 options;

- use the symfony argument resolver: https://github.com/msgphp/msgphp/blob/master/src/User/Infra/Security/UserValueResolver.php
- use doctrine param converter: https://github.com/msgphp/msgphp/blob/master/src/User/Infra/Security/UserParamConverter.php

both are available out-of-the box:

```
/**
 * @ParamConverter("user", converter="doctrine.orm", class="App:User", options={"current": true})
 */
public function someAction(User $currentUser = null, Environment $twig) {
    return new Response($twig->render('template.html.twig', ['user' => $currentUser]));
}
```

If you dont use doctrine param converters, you can simply leave out the annotation. It should use the argument resolver in that case :)

**Comment by crabnky** [comment]
Thanks, tried both ways, but I'm getting null every time. Did I miss something?

**Comment by ro0NL** [comment]
Well ... are you logged in? :) Do you see the username in the profiler toolbar?

Using null-ability implies you expect either an authenticated user or a guest. If you need to be "logged in", leave out `= null`.

Either way, it should work :) not sure if something broke in the meanwhile. I can try to reproduce soon-ish.

**Comment by ro0NL** [comment]
When using the param converter annotation you also need `
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;` btw :)

**Comment by crabnky** [comment]
Heh, I'm logged in. :)))
I had a mistake in annotation, but now when I use param converter I see `Invalid option(s) passed to @ParamConverter: current`, still got null when using argument resolver.
When I add
```
    MsgPhp\User\Infra\Security\UserValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
```
to services, the param converter error is not present (even if I add the param converter annotation), but still got null.

**Comment by ro0NL** [comment]
@crabnky we got it wrong :) see https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/564

basically the correct annotation would be `@ParamConverter("currentUser", options={"current": true})` (leave out `class`).

**Comment by ro0NL** [comment]
See also https://github.com/msgphp/msgphp/pull/99/files for how to do it in 0.2, much better IMHO :)

**Comment by ro0NL** [comment]
@crabnky  can we close?

**Comment by crabnky** [comment]
Not sure if this is related, but I noticed the following change:
Here is my sample user edit controller:
```
use App\Entity\User;
...

/**
 * @Route(
 *     "/users/{id}/edit",
 *     name = "users_edit",
 *     requirements = {
 *         "id" = "\d+"
 *     }
 * )
 * @param Request $request
 * @param User $user
 *
 * @return Response
 */
public function index(Request $request, User $user)
{
    ...
}
```
Current behavior is that $user is always a current logged in user. No matter of id in the route.
Before, the $user was a user with corresponding id - so for example for the route `/users/11/edit` the user with id 11 was taken. For now it is a current logged in user. Is this a correct behavior?

As I said I'm not 100% sure that the change is caused by updating msgphp/user, but this was the only thing I updated.

**Comment by ro0NL** [comment]
>  Is this a correct behavior?

Depends. In the demo app i disabled auto conversion: https://github.com/msgphp/symfony-demo-app/blob/master/config/packages/sensio_framework_extra.yaml and always use explicit param converters: https://github.com/msgphp/symfony-demo-app/blob/master/src/Controller/User/ConfirmRegistrationController.php#L16

So without annotation no param converter matches, and thus the argument resolver is used eventually.

**Comment by ro0NL** [comment]
@crabnky i made a mistake.. the priority set was bugging. Now gone :) https://github.com/msgphp/user-bundle/commit/42a64e44a4175582cfcb43637f03fc18f0880d36 (dev-master)

If you use doctrine param converters auto mapping by id is preserved (`/users/11/edit`). If you explicitly want the current user, use:

```php
/**
 * @ParamConverter("user", converter="msgphp.current_user")
 */
```

See also https://github.com/msgphp/symfony-demo-app/commit/66becda49cf43b470d86fa1fcc9c2fe2761479dd

**Comment by ro0NL** [comment]
@crabnky in twig there's now also `msgphp_user.user` to get the current user, if any, directly.

**Comment by ro0NL** [comment]
@crabnky i dont think there's much left to do here. Please re-open / raise an issue if you experience anything wrong.

**Comment by crabnky** [comment]
Thanks much, was few days off the project.
