### ISSUE TITLE
Add demo admin interface

### ISSUE THREAD

**Issue by ro0NL** [msgphp/symfony-demo-app#24]
- /admin + ROLE_ADMIN
  - list all users with impersonate link
  - paginated
- nav update for admins

**Comment by ro0NL** [comment]
After #28 we could do this API first :) 

Im thinking https://api-platform.com/docs/admin :D

**Comment by GawainLynch** [comment]
That one kinda lines up with something else :wink:

**Comment by ro0NL** [comment]
From https://medium.com/p/ceeefe2a2e9/info it may be worth checking EasyAdmin also and demo both admin environments (API first / traditional).

https://github.com/EasyCorp/EasyAdminBundle

**Comment by kochen** [comment]
Hey @ro0NL,
just my 2cents here, EasyAdmin is a very good solution, but it uses ORM/Crud directly, which would "contradict" a bit the Command Pattern way.
It is possible though to write your own (admin) controllers, but you'll have to do them manually for each and every entity - maybe for an "only user" system/demo is fine...


P.S, you link to Medium requires login (for some unclear reason)

**Comment by ro0NL** [comment]
@kochen 

> would "contradict" a bit the Command Pattern way.

yeah... totally :") but in theory it should be possible, _simply_ for having those ORM entities. Im curious regarding the out-of-the-box experience.

> It is possible though to write your own (admin) controllers, but you'll have to do them manually for each and every entity - maybe for an "only user" system/demo is fine...

Agree. For demo purpose that seems reasonable.. although the "default" way seems preferred.

Link updated. Thx.

**Comment by kochen** [comment]
@ro0NL fair point, if eventually it works out of the box because you have those entities that could be a great benefit.

**Comment by kochen** [comment]
@ro0NL like this:
![image](https://user-images.githubusercontent.com/106042/39430721-e929f9ba-4c8e-11e8-8da8-a6155ddd8278.png)

**Comment by ro0NL** [comment]
@kochen sweeet :) can you submit a PR with your progress so far?

**Comment by kochen** [comment]
@ro0NL done!
we still need to figure out how to make the edit form work.

**Comment by divined** [comment]
One year left (

**Comment by ro0NL** [comment]
:D @divined personally i gave up on EasyAdmin, moving forward with React Admin +ApiPlatform: #59

i need to merge a working example for sure :)

**Comment by Pictor13** [comment]
Hey @ro0NL would you mention specifically why did you give up on EasyAdmin?

----- 
Because... I am struggling with its structure as well.
Basic CRUD is great with it, but some type of extendibility is simply painful and requires quite some overriding; and it's tough to implement DDD practices: strict separation of concerns & immutability in particular.

**Comment by ro0NL** [comment]
I find that some type of extendibility is simply painful and requires quite some overriding; and it's tough to implement DDD practices: strict separation of concerns & immutability in particular.

:grin: this.

Today, im using APIplatform + separate Vue based frontend. I think REST based JSON+LD / GraphQL is today's practice. Thus separation of concerns out-of-the-box.

Even with API platform im experiencing some of the issues pointed out above (mapping API to entities). But eventually it's a software architecture thingy, thus developer's choice. 

So for MsgPHP the frontend is low-prio, as we focus on the API first.

**Comment by ro0NL** [comment]
closing as per https://github.com/msgphp/symfony-demo-app/pull/59#issuecomment-574803359

im focusing on the backend/API part anyway.
