### ISSUE TITLE
Add a docker-compose.yml

### ISSUE THREAD

**Issue by Evertt** [msgphp/symfony-demo-app#39]
I think it would be nice to have a docker container optimized for this symfony-demo-app that users can just `$ docker-compose up -d` and immediately start working with, don't you think?

Preferably using the most lightweight images possible, using exactly what the app needs and nothing more. Like I read an [article](https://very-serio.us/2018/02/27/zen-minimalism-with-distroless-images/) a few weeks ago about Google creating something called "distroless" images which are exactly that. Could we use that?

**Comment by ro0NL** [comment]
Yes, for sure :) 

I use this at home https://github.com/ro0NL/workdir for generic purpose. Mostly if we can ease the nginx+ssl+local domain setup that be great.

Currently im also experimenting with Lando (https://github.com/lando/lando)... i tend to believe you can build any stack with it :)

**Comment by ro0NL** [comment]
@Evertt any news? By now im leaning to add a `.lando.yml` instead =/

see also https://github.com/ro0NL/symfony-lando

**Comment by Evertt** [comment]
Yeah let's do that, at least for now. I don't really have the time to dive into the distroless images of google.
