### ISSUE TITLE
Invalid service "data_collector.security"

### ISSUE THREAD

**Issue by crabnky** [msgphp/symfony-demo-app#63]
Morning. :)

I just updated from 0.5 to 0.6 and getting this:
`Invalid service "data_collector.security": method "MsgPhp\User\Infra\Security\DataCollector::__construct()" has no argument named "$factory". Check your service definition.`
Did I miss something?

**Comment by crabnky** [comment]
OK, I had this in `composer.json`:
`"msgphp/user-bundle": "^0.5.0"`
so the user bundle was still in version 0.5.0.
I manually changed this to
`"msgphp/user-bundle": "^0.6.0"`
and now all is fine.
Should the composer update all packages (domain, user, user-bundle) to latest version?

**Comment by ro0NL** [comment]
Right, let's switch dependencies to use carets :)

https://github.com/msgphp/msgphp/blob/475249a290c803875dfef5a03a4c3fc54a59d8f9/src/UserBundle/composer.json#L21

for now `composer update msgphp/*` is the best :)

**Comment by crabnky** [comment]
This can be closed I think. :)
Thanks.

**Comment by ro0NL** [comment]
See https://github.com/msgphp/msgphp/commit/135b64b113133c6bb4f7ce4ee9bd1898cc935e7e
