### ISSUE TITLE
User emails table can be changed from another application?

### ISSUE THREAD

**Issue by crabnky** [msgphp/symfony-demo-app#64]
Hi,
Regarding the multiple email login - what if we have another application using the same database, which can modify user emails table? In such case the changes won't be reflected in the username table, right?

**Comment by ro0NL** [comment]
If you modify the table directly, then no. In that case you can run `bin/console user:synchronize:usernames`.

Otherwise, when using the ORM itself, it's synced by default using the entity listener: https://github.com/msgphp/msgphp/blob/master/src/User/Infra/Doctrine/Event/UsernameListener.php

**Comment by ro0NL** [comment]
@crabnky yes, that's what https://github.com/msgphp/msgphp/pull/197 is about :) it allows to enable/define the `Username` entity in your app, without configuring `username_lookup` (for Doctrine).

**Comment by crabnky** [comment]
Uh, the last item in https://github.com/msgphp/msgphp/issues/196 solves my problem I think. I overlooked this, sorry. :( When do you expect this to be released?

**Comment by ro0NL** [comment]
aiming for it this Wednesday :)

Currently `username_lookup` is only handled by doctrine,  so configuring e.g. 
 `msgphp_user.doctrine.sync_usernames: false` would be the same as not configuring the `username_lookup`.

But for future purposes it's possible to enable the username lookup and disable doctrine handling.

**Comment by ro0NL** [comment]
see `0.7@dev`
