### ISSUE TITLE
Multiple email: forgot password looks for email in users table...

### ISSUE THREAD

**Issue by crabnky** [msgphp/symfony-demo-app#66]
Hi,

What about forgot password when using multiple email login feature? I entered the alternate email in the forgot password form and got `Call to a member function getId() on null` error. I checked the queries and I can see that system looks for users table for user with specified credential email, and it gets nothing of course because this email exists in the `username` table...

**Comment by ro0NL** [comment]
@crabnky 

> Call to a member function getId() on null

Do you have a stacktrace?

**Comment by crabnky** [comment]
Stack Trace:
```
Error:
Call to a member function getId() on null

  at src\Controller\Contact\ForgotPasswordController.php:38
  at App\Controller\Contact\ForgotPasswordController->__invoke(object(Request), object(FormFactory), object(FlashBag), object(TraceableMessageBus), object(EntityManager))
     (vendor\symfony\http-kernel\HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\http-kernel\HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\http-kernel\Kernel.php:188)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public\index.php:37)
```
![exception](https://user-images.githubusercontent.com/2010148/45948955-411dc780-bffa-11e8-83f3-f2febb8c904b.png)
![logs](https://user-images.githubusercontent.com/2010148/45948960-4713a880-bffa-11e8-80e2-31ed5fd6c144.png)

Let me know if you need enything else.

**Comment by ro0NL** [comment]
You're not getting an entity from doctrine based on given email, `$user` is null. Not sure why you call the `User` entity a `Contact`.. but that shouldnt matter.

If you want to find a user by either primary or secondary email (or any of the lookups configured under `msgphp_user.username_lookup), you'll need to use `UserRepositoryInterface::findByUsername` or handle the case your self.

See e.g. https://github.com/msgphp/symfony-demo-app/blob/master/src/Controller/User/ForgotPasswordController.php#L26

**Comment by crabnky** [comment]
Uhhhhhh, sure, fool me. :|
Let's assume this issue was never raised. :))
About Contacts - I have to work on existing database and I have limited ability to modify it, so I have to work with already existing solutions. I'm not a fan of many of them, but... it is what it is. :(
