### ISSUE TITLE
msgphp_user.current.email takes always credential email

### ISSUE THREAD

**Issue by crabnky** [msgphp/symfony-demo-app#67]
When I log in using alternate email I expect this email is stored in msgphp_user.current.email - instead I always get value from credential_email from user table.

**Comment by ro0NL** [comment]
Well ... the user's primary email doesnt change, regardless the username that was used to login with.

I think we can track the origin username in the security users (stored in the session), e.g. `SecurityUser::getOriginUsername(): string`, or in twig: `{{ app.user.originUsername }}`.

**Comment by crabnky** [comment]
Uh, I forgot that anything can be used as username, not only email. My bad, sorry.
Good idea with `originUsername`. :)

**Comment by ro0NL** [comment]
see https://github.com/msgphp/msgphp/pull/204

**Comment by ro0NL** [comment]
fixed in `^0.7@dev`
