### ISSUE TITLE
Multiple email - forgot password always sends email to primary email

### ISSUE THREAD

**Issue by crabnky** [msgphp/symfony-demo-app#68]
Hello,

As far as I can see the forgot password feature sends email to user primary email, regardless of email entered into the form, right? The email entered into forgot password form is used only to find user, then email is sent to users primary email...
This may be confusing, I think.

**Comment by ro0NL** [comment]
Hi @crabnky 

that's correct, and how things work today in the demo-app.

I think we can do the same thing as https://github.com/msgphp/msgphp/pull/204, so we have `SomeUserEvent::$originUsername` and `SomeUserEvent::$user->getCredential()->getUsername()` in all user related events. Feel free to make the change :)
