### ISSUE TITLE
Documentation for implementing email confirmation

### ISSUE THREAD

**Issue by kironet** [msgphp/symfony-demo-app#85]
Hi,

Can we get a documentation about how to implement User Email Confirmation? 
I can see it's implemented in this demo, but it would be nice to have a documentation on how to implement it to freshly installed bundle.

**Comment by ro0NL** [comment]
Hey @kironet 

I was kinda working on this :) https://github.com/msgphp/msgphp/issues/228 so the default case can be generated. However, for sending e-mail im not sure still ... as we introduce Swiftmailer&co with it. Perhaps wait for the official Symfony Mailer component to arrive first. (AFAIK it'll happen soonish).

Perhaps it's better to add some docs about the subject, see https://github.com/msgphp/msgphp/issues/115
